env:
  es6: true
  node: true
plugins:
  - lodash-fp
extends: 
  - 'eslint:recommended'
  - 'plugin:lodash-fp/recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - off
